config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up', to: 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources 'quotes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true

  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :company

  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  # broadcast_ is syncronous by default

  # ACTION_to is asyncronous
  # after_create_commit -> { broadcast_prepend_later_to 'quotes' }
  # after_update_commit -> { broadcast_replace_later_to 'quotes' }
  # after_destroy_commit -> { broadcast_remove_to 'quotes' }
  # equivalent to
  # broadcasts_to ->(_quote) { 'quotes' }, inserts_by: :prepend
  broadcasts_to ->(quote) { [quote.company, 'quotes'] }, inserts_by: :prepend # scope the channel broadcast

  # def update_quotes_list
  # broadcast_prepend_to 'quotes',
  #                      partial: 'quotes/quote', # default
  #                      locals: { quote: self }, # default is self
  #                      target: 'quotes' # default is plural

  # broadcast_prepend_to 'quotes' # this is already enough
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :validatable

  belongs_to :company

  def name
    email.split('@').first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
  # before_action -> { sleep 2 }
  helper_method :current_company

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home; end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  helper_method :quote, :quotes

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    quote.assign_attributes(**quote_params, company: current_company)

    if quote.save
      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = "Quote was successfully created." }
        format.html { redirect_to quotes_path, notice: 'Quote was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if quote.update(quote_params)
      # redirect_to quotes_path, notice: 'Quote was successfully updated.'
      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = 'Quote was successfully updated.' }
        format.html { redirect_to quotes_path, notice: 'Quote was successfully updated.' }
      end
    else
      render :new
    end
  end

  def destroy
    quote.destroy!

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = 'Quote was successfully destroyed.' }
      # format.turbo_stream { render turbo_stream: turbo_stream.remove(quote) }
      format.html { redirect_to quotes_path, notice: 'Quote was successfuly destroyed.' }
    end
  end

  private

  def quotes
    @quotes ||= current_company.quotes.ordered
  end

  def quote
    @quote ||= if %w[new create].include?(action_name)
      Quote.new
    else
      current_company.quotes.find(params[:id])
    end
  end

  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def turbo_render_flash
    turbo_stream.prepend 'flash', partial: 'layouts/flash'
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow animate-appear-then-fade" 
    role="alert" data-controller="flash" data-action="animationend->flash#remove">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="bg-white border-gray-200 px-4 lg:px-6 py-2.5">
  <nav class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl" aria-label="Global">
    <% if user_signed_in? %>
      <div class="self-center text-xl font-semibold whitespace-nowrap">
        <%= current_company.name %>
      </div>
      <div class="lg:flex lg:flex-1 lg:justify-end">
        <div class="text-gray-800 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 focus:outline-none">
          <%= current_user.name %>
        </div>
        <%= button_to "Sign out",
                    destroy_user_session_path,
                    method: :delete,
                    class: "inline-flex items-center justify-center w-full px-4 py-2 text-sm font-medium " \
                      "text-gray-900 bg-white border border-gray-200 rounded-lg md:w-auto focus:outline-none "\
                      " hover:bg-gray-100 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-gray-200 " %>
      </div> 
    <% else %>
      <div class="self-center text-xl font-semibold whitespace-nowrap">
        Quote Editor
      </div>
      <div class="lg:flex lg:flex-1 lg:justify-end">
        <%# <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Sign in <span aria-hidden="true">&rarr;</span></a> %>
        <%= link_to "Sign in",
                  new_user_session_path,
                  class: "inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold " \
                    "text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 " \
                    "focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>      
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div id="flash" class="container mx-50 flex z-50 fixed top-30 left-0 -translate-x-1/2 left-1/2 justify-center">
      <%= render "layouts/flash" %>
    </div>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<main class="w-full pr-1 pl-1 mx-auto bg-white">
  <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12">
    <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl">Quote editor</h1>
    <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48">A blazing fast quote editor built with Hotwire</p>

    <% if user_signed_in? %>
      <%= link_to "View quotes", quotes_path, class: "inline-flex items-center rounded-lg bg-indigo-600 px-3" \
          " hover:cursor-pointer" \
          " py-2 text-base font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline" \
          " focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path, class: "inline-flex items-center rounded-lg bg-indigo-600 px-3" \
          " hover:cursor-pointer" \
          " py-2 text-base font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline" \
          " focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    <% end %>
  </div>
</main>

app/views/quotes/_empty.html.erb
<div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12 border rounded hidden only:block">
  <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48">You don't have any quotes yet!</p>

  <%=
    link_to "Add Quote",
    new_quote_path,
    class: "inline-flex items-center rounded-md bg-indigo-600 px-3" \
        " hover:cursor-pointer" \
        " py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline" \
        " focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600",
    data: { turbo_frame: dom_id(Quote.new) } %>
</div>

app/views/quotes/_form.html.erb
<%= form_with model: quote, html: { class: "flex flex-wrap gap-1 bg-white shadow-md" \
  " rounded px-8 pt-6 pb-8 mb-4" } do |form| %>
  <% if quote.errors.any? %>
    <div class="w-full p-1 text-rose-950 rounded bg-slate-300">
      <%= quote.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <div class="flex-1">
    <%= form.label :name, class: "sr-only" %>
    <%= form.text_field :name, class: "block invalid:border-red-500 shadow appearance-none border rounded w-full" \
      " py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <%= link_to "Cancel", quotes_path, class: "inline-flex items-center rounded-md bg-white" \
      " px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
  <%= form.submit class: "inline-flex items-center rounded-md bg-indigo-600 px-3 hover:cursor-pointer" \
    " py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline" \
    " focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"  %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="flex gap-2 justify-between items-center mb-1 bg-slate-400 rounded-md p-2">
    <%= link_to quote.name, 
        quote_path(quote), 
        data: { turbo_frame: "_top" } %>
    <div class="flex flex[0_0_auto] self-start gap-1 justify-between items-center mb-2 p-1 ">
      <%= button_to "Delete", 
          quote_path(quote), 
          method: :delete, 
          class: "inline-flex items-center rounded-md bg-white" \
        " px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
      <%= button_to "Edit", edit_quote_path(quote), method: :get, class: "inline-flex items-center rounded-md bg-white" \
        " px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" %>
    </div>
  </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", quote %>

<%= turbo_stream.update Quote.new, "" %> <%# clear form and remove new  %>

<%= turbo_render_flash %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove quote %>

<%= turbo_render_flash %>

<%# unless current_company.quotes.exists? %>
  <%#= turbo_stream.update Quote.new do %>
    <%#= render "quotes/empty" %>
  <%# end %>
<%# end %>

app/views/quotes/edit.html.erb
<main class="w-full pr-1 pl-1 mx-auto">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(quote) %>

  <div class="flex flex-wrap gap-3">
    <h1 class="text-4xl">Edit quote</h1>
  </div>

  <%= turbo_frame_tag quote do %>
    <%= render "form", quote: quote %>
  <% end %>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from [current_company, "quotes"] %>
<%# <%= turbo_stream_from "quotes" %>

<main class="w-full pr-1 pl-1 mx-auto">
  <div class="flex flex-wrap gap-3 justify-between mt-3 mb-4">
    <h1 class="text-4xl">Quotes</h1>
    <%= link_to "New quote", new_quote_path, 
      class: "inline-flex items-center rounded-md bg-indigo-600 px-3" \
        " hover:cursor-pointer" \
        " py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline" \
        " focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600",
        data: { turbo_frame: dom_id(Quote.new) }
    %>
  </div>

  <%= turbo_frame_tag Quote.new %>
  <%#= turbo_frame_tag Quote.new do %>
    <%# if quotes.none? %>
      <%#= render "quotes/empty" %>
    <%# end %>
  <%# end %>

  <%= turbo_frame_tag "quotes" do %>
    <%= render "quotes/empty" %>
    <%= render quotes %>
  <% end %>
</main>

app/views/quotes/new.html.erb
<main class="w-full pr-1 pl-1 mx-auto">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

  <div class="flex flex-wrap gap-3">
    <h1 class="text-4xl">New quote</h1>
  </div>
  <%= turbo_frame_tag quote do %>
    <%= render "form", quote: quote %>
  <% end %>
</main>

app/views/quotes/show.html.erb
<main class="w-full pr-1 pl-1 mx-auto">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="flex flex-wrap gap-3">
    <h1 class="text-4xl"><%= quote.name %></h1>
  </div>
</main>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace quote %>

<%= turbo_render_flash %>